### ISSUE TITLE
[Question] Protection from mobs damage

### ISSUE THREAD

**Issue by GTP95** [minetest-mods/areas#50] opened 2020-12-11 09:44 UTC
Hello,
I'm using this mod on a server running Minetest Game to protect an area. Now I'm thinking about installing mods to add mobs, but I was wondering: will this mod also protect the area from damages caused by mobs?
Thank you for the information,

GTP

**Comment by S-S-X** [comment] 2021-01-18 11:22
> will this mod also protect the area from damages caused by mobs?

Yes, area is protected from damage caused by mobs if mobs do protection checks properly using minetest.is_protected, there's some mobs that wont do this and some that will.

Also some mobs with splash explosion damage did protection check only at impact point and if that was not protected then explosion could destroy protected nodes, some fixed some not fixed.

Best to mine test it yourself with mobs as mobs has to do protection checks.

**Comment by GTP95** [comment] 2021-01-18 11:35
Thanks!Giacomo Tommaso Petrucci
-------- Messaggio originale --------Da: SX <notifications@github.com> Data: 18/01/21  12:23  (GMT+01:00) A: minetest-mods/areas <areas@noreply.github.com> Cc: Giacomo Tommaso Petrucci <giacomo.tom.petrucci@tiscali.it>, Author <author@noreply.github.com> Oggetto: Re: [minetest-mods/areas] [Question] Protection from mobs damage (#50) 

will this mod also protect the area from damages caused by mobs?

Yes, area is protected from damage caused by mobs if mobs do protection checks properly using minetest.is_protected, there's some mobs that wont do this and some that will.
Also some mobs with splash explosion damage did protection check only at impact point and if that was not protected then explosion could destroy protected nodes, some fixed some not fixed.
Best to mine test it yourself with mobs as mobs has to do protection checks.

**Comment by mckaygerhard** [comment] 2021-11-01 13:29
**i will added a note:** that protection is not from concecuences.. as .. _only at impact point and if that was not protected then explosion could destroy protected nodes_ 

so if someone put lava and that lava raised the protection area. of course will affect.. protection is only in active actions and if the mobs mods supported.. 

close this issue .. as information.

**Closed as completed** 2022-02-04 15:29 UTC
